# https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types
resources:
- name: ib-trading-net
  type: compute.v1.network
  properties:
    name: ib-trading-net
    autoCreateSubnetworks: false
- name: ib-trading-subnet
  type: compute.v1.subnetwork
  properties:
    name: ib-trading-subnet
    network: $(ref.ib-trading-net.selfLink)
    region: europe-southwest1
    ipCidrRange: 10.172.0.0/20
    privateIpGoogleAccess: true
- name: ib-trading-net-allow-internal
  type: compute.v1.firewall
  properties:
    name: ib-trading-net-allow-internal
    network: $(ref.ib-trading-net.selfLink)
    direction: INGRESS
    allowed:
    - IPProtocol: all
    sourceRanges: ["10.172.0.0/20"]
    priority: 1000
- name: ib-trading-net-allow-ssh-bastion-host
  type: compute.v1.firewall
  properties:
    name: ib-trading-net-allow-ssh-bastion-host
    network: $(ref.ib-trading-net.selfLink)
    direction: INGRESS
    allowed:
    - IPProtocol: TCP
      ports: ["22"]
    sourceRanges: ["0.0.0.0/0"]
    targetTags: ["bastion-host"]
    priority: 1000
- name: nat-router
  type: compute.v1.router
  properties:
    network: $(ref.ib-trading-net.selfLink)
    region: europe-southwest1
    nats:
    - name: nat-config
      sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
      natIpAllocateOption: AUTO_ONLY
      logConfig:
        enable: true
        filter: ALL
- name: ib-trading
  type: container.v1.cluster
  properties:
    zone: europe-southwest1-a
    cluster:
      name: ib-trading
      nodePools:
      - name: default-pool
        initialNodeCount: 1
        config:
          machineType: e2-small
          diskSizeGb: 10
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring
          tags: ["ib-trading-node"]
        management:
          autoUpgrade: true
          autoRepair: true
      network: $(ref.ib-trading-net.selfLink)
      subnetwork: $(ref.ib-trading-subnet.selfLink)
      initialClusterVersion: latest
      privateClusterConfig:
        enablePrivateNodes: true
        enablePrivateEndpoint: true
        masterIpv4CidrBlock: 172.16.0.0/28
      masterAuthorizedNetworksConfig:
        enabled: true
      ipAllocationPolicy:
        useIpAliases: true
- name: bastion-host
  type: compute.v1.instance
  properties:
    machineType: zones/europe-southwest1-a/machineTypes/e2-small
    zone: europe-southwest1-a
    networkInterfaces:
    - network: $(ref.ib-trading-net.selfLink)
      subnetwork: $(ref.ib-trading-subnet.selfLink)
    tags:
      items: ["bastion-host"]
    serviceAccounts:
    - email: 786272790820-compute@developer.gserviceaccount.com
      scopes:
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/source.read_only
    disks:
    - boot: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-11
        diskSizeGb: 10
      autoDelete: true
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get -y install kubectl git
          gcloud container clusters get-credentials ib-trading --zone europe-southwest1-a --internal-ip
