apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ib-trading
    ib-mode: paper
    purpose: gateway
  name: ib-gw-paper-volume-0
  namespace: ib-trading
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ib-trading
    ib-mode: paper
    purpose: gateway
  name: ib-gw-paper
  namespace: ib-trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ib-trading
      ib-mode: paper
      purpose: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ib-trading
        ib-mode: paper
        purpose: gateway
    spec:
      containers:
      - env:      
        - name: GCP_PROJECT_ID
          value: "api-project-786272790820"
        - name: TRADING_MODE
          value: paper
        - name: TWSPASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials-ib-gw-paper-prod
              key: ib-password
        - name: TWSUSERID
          valueFrom:
            secretKeyRef:
              name: credentials-ib-gw-paper-prod
              key: ib-user
        image: eu.gcr.io/api-project-786272790820/ibc:latest
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 10
        name: ib-gw-paper
        ports:
        - containerPort: 4003
          name: ib-gw
          protocol: TCP
      - image: eu.gcr.io/api-project-786272790820/ib-gateway-healthcheck:latest
        name: ib-gw-paper-healthcheck
        ports:
        - containerPort: 8000
          name: healthcheck
          protocol: TCP
      restartPolicy: Always
      volumes:
      - name: ib-gw-paper-volume-0
        persistentVolumeClaim:
          claimName: ib-gw-paper-volume-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ib-trading
    ib-mode: paper
    purpose: gateway
  name: ib-gw-paper
  namespace: ib-trading
spec:
  ports:
  - name: ib-gw
    port: 4003
    protocol: TCP
  selector:
    app: ib-trading
    ib-mode: paper
    purpose: gateway
  type: ClusterIP
